### PR TITLE
V1.3

### PR DESCRIPTION
**Pull request by oharaandrew314**
This update focuses on fixing annoyances, in order to provide a better general UX.
A major refactor was done, reducing lines of code by an estimated 25%.

[Download RC1](https://drive.google.com/open?id=0ByGq5aXm4AHQOGo2YmFuYmpYWTg&authuser=0)
[Download RC2](https://drive.google.com/open?id=0ByGq5aXm4AHQYjNlUGZfV2oyZDA&authuser=0)

@cgruber, could you please verify that the right-click context menu now works on OSX?
@apemanzilla, a ton of refactoring has been done.  Please give a general run through of everything you can think of.

###### LEGACY BREAKING CHANGES:
- You will need to re-add and re-download all your mods
  - mods list file schema has been simplified
  - mod zip and image caches are now stored in GameData directory
  - mod id generation has been changed

- New Features
  - Add an options field to set KSP Launch Options
  - Updating the options will no longer require an app restart
  - Now scans the GameData directory to see which mods are enabled
  - Now scrapes Github using the API, by default
    - If the API limit is reached, will fallback to the HTML scraper
  - Can now parse versions of mods and use those when checking for updates
  - Progress bars will now appear immediately after launching a task, and their max progress will be set once it has been determined afterwards
- Fixes
  - Mod file caches between KSP installations are now separate
    - This fixes issues when updating or deleting a mod in one installation, which would then affect the other
    - Caches are now stored in a "TinkerTime" directory within your KSP installation
  - Options Window to have correct number of rows
- Other Changes
  - Removed Nimbus UI
  - Tinker Time now updates itself using KerbalStuff, rather than Github
  - ModuleManager has been further integrated as a mod, (as opposed to a special entity)
  - Mod list file no longer needs to save image URLs and enabled state
  - Refactor Unit Test resource loading
  - Major general refactor

### CODE REVIEW

**Comment by apemanzilla** [comment]
I'm currently away from my computer for another day give or take but remind me then and I'll check and test everything.

**Comment by oharaandrew314** [comment]
@apemanzilla, just reminding you to check out the JAR, like you asked me to.

**Comment by apemanzilla** [comment]
Except for one minor problem (I'll make an issue) everything seems to be working fine.

**Comment by cgruber** [comment]
Sad about the re-adding all your mods.  It would be nice if there was a way to export that list in a neutral way that could be re-added.  In fact, that might make a nice feature - load a list of mods from a file, so people can share mod sets.

**Comment by cgruber** [comment]
And OSX issue seems resolved.

**Comment by apemanzilla** [comment]
Import/Export is already possible - check the menubar at the top.

**Comment by cgruber** [comment]
Oooh!  Missed that. 

Also, some really nice changes and some nice re-organization of code.  Kudos!

**Comment by oharaandrew314** [comment]
@cgruber, glad you appreciate the changes.

@apemanzilla, I'm not sure if the import/export will work, unless you've given it a shot yourself.  I'll try it myself.

**Comment by cgruber** [comment]
I'm trying out the import/export for fun.  Worst-case I get a .json with the urls I need that I can grep for a list.  Best case, it just works. :D

**Comment by cgruber** [comment]
Anyway - I say ship it. :)

**Comment by apemanzilla** [comment]
Wait!
I can't seem to enable/disable mods any more. I get an error immediately after launch:

**Comment by oharaandrew314** [comment]
Does anyone have an old TinkerTime.json mods file (pre 1.3) that they can send me to test the import/export on?

**Comment by oharaandrew314** [comment]
@apemanzilla, I tried out your mods file.  I can confirm that some errors do occur due to some migration issues, and the migration causes duplicates (I will fix this before shipping).  However, I cannot reproduce any errors on startup, nor can I reproduce your particular error.

**Comment by apemanzilla** [comment]
Hmm. Alright, I'll look into it a bit.

**Comment by oharaandrew314** [comment]
@apemanzilla, I'm making progress with deleting the conflicts from the migration, but for some reason I'm unable to disable your Transfer Window Planner and KerbalAlarmClock mods.  It's a very strange phenomenon.  The disable workflow is submitted to the executor, but the delete task is never called.

**Pull request merged**
