### PR TITLE
Version 1.2 Release

### PR DESCRIPTION
**Pull request by oharaandrew314**
- New Features
  - Automatically check for TinkerTime update, and prompt user if new version is available
  - Mod Page Caching to now persist for 10 minutes (rather than just for a single workflow)
- Fixes
  - Update Github Crawler to match new DOM
  - Fix issue where illegal file characters were causing some mods to fail to download
  - "Update All" button to only update mods which have an update available

@apemanzilla and @cgruber, would you care to run some smoke tests on master or the Release Candidate?

[Download RC 1 ](https://drive.google.com/open?id=0ByGq5aXm4AHQcDhjV2czYmpFTjA&authuser=0)
[Download RC 2](https://drive.google.com/open?id=0ByGq5aXm4AHQQnA2X0ZRak9qSUU&authuser=0)

### CODE REVIEW

**Comment by apemanzilla** [comment]
Sure, I'll test it when I get home later.

**Comment by cgruber** [comment]
Checking on it.

**Comment by cgruber** [comment]
Releas candidate looks good, though I'm finding a regression that I realize as I dig in was in head and in a few versions prior (1.1.1 at least, possibly 1.1).  The right-click context menus on the mods in the list is unclickable. I get three options (enable/disable, update, delete) but none of those three menu items actually work.   There is a workaround, which is just to use the top menu items instead of the context menu.  I'll file it as a separate issue.

Considering on my machine (Mac OS X) it exists in several versions prior, I would not hold up 1.2 for it. It could be my machine and/or config, or it could be a bug in the wild.  The issues for which 1.2 was rolled seem to be pretty much dealt with.  

Specifically, I get proper computation of times, such that things that shouldn't be listed as having an update are correctly showing no new update, and the issues with github scraping seem to be fine. Also no new redirects to auth.curse.com.

**Comment by cgruber** [comment]
Now if only the game would play for any length of time (I'm having the Mac OS X 10.10 memory issues that others are having with 0.90)

**Comment by oharaandrew314** [comment]
@cgruber, the right-click menu bug is interesting.  I cannot reproduce it on my Windows machine.

**Comment by cgruber** [comment]
Crap - I'm still having some issues with github... right after you commit it. :(  

Can you try adding https://github.com/ClawKSP/KSP-Stock-Bug-Fix-Modules as a new plugin?  I'm getting "this plugin has no releases" or whatever.

**Comment by oharaandrew314** [comment]
@cgruber, I managed to reproduce the issue.  I will reopen #187

**Comment by cgruber** [comment]
Whew.  Sorry for the late catch.

**Comment by apemanzilla** [comment]
I haven't sen any major issues yet aside from #187 either.

**Comment by oharaandrew314** [comment]
@cgruber  and @apemanzilla, would you mind verifying that #187 is resolved, please?  You can compile from branch v1.2, or [download RC 2](https://drive.google.com/open?id=0ByGq5aXm4AHQQnA2X0ZRak9qSUU&authuser=0)

**Comment by apemanzilla** [comment]
All good here.

**Comment by cgruber** [comment]
Checking...

**Comment by cgruber** [comment]
Seems good to me.

**Comment by oharaandrew314** [comment]
Released on Github and Kerbalstuff!

**Comment by cgruber** [comment]
+1!

**Pull request merged**
