### PR TITLE
Mod Enabling to be file-driven

### LINKED ISSUE #211: KerbalAlarmClock and TransferWindowPlanner will not disable while both are enabled
Both of these mods use the same module, TriggerAu, as he is the author for them both.  They will refuse to be disabled, since they share a module folder.  Come up with a way to preserve dependencies of other mods, yet still be able to disable these mods individually.

### PR DESCRIPTION
**Pull request by oharaandrew314**
Rather than enabling mods based on their modules (folders to install to GameData), mods are now enabled by their individual files.  This should fix #211.

@apemanzilla, could you verify this fix?  A massive refactor was required, so I will need some general testing in regards to mod enabling, deleting, and updating, too.

Your mods json will no longer work.  I have changed the path of the file for forwards compatibility.  I will update the readme soon.

[Download RC3](https://drive.google.com/open?id=0ByGq5aXm4AHQQlVPQk85SU1UNzA&authuser=0)
[Download RC4](https://drive.google.com/open?id=0ByGq5aXm4AHQbi1wN0JlVHktcXc&authuser=0)
[Download RC5](https://drive.google.com/open?id=0ByGq5aXm4AHQQ0kwV0IwSlNoY2M&authuser=0)

### CODE REVIEW

**Comment by cgruber** [comment]
Addresses #215

**Comment by cgruber** [comment]
Ok - this seems to fix nearly everythign.... except that alternate resource panel no longer enables.  I click it, it spins for a moment, then the icon flashes to active, then immediately reverts to inactive.   Checking now to see if it is actually enabled and maybe the detection is off.

**Comment by cgruber** [comment]
The files seem to be in the GameData folder under TriggerTech :/

**Comment by cgruber** [comment]
Yep.  If I blow away everything, and re-install KerbalAlarmClock, I get AlternateResourcePanel installed for free... but not detected by TinkerTime.

**Comment by oharaandrew314** [comment]
Yes, I can replicate this issue.  Curious.

**Comment by oharaandrew314** [comment]
@cgruber, I think I have fixed it.  The problem is that my enabler doesn't copy over empty directories.  However, testing whether a mod was enabled checked that all the files and folders were there.

It just so happens that Alternate Resource Panel contained an empty directory in the zip.  So, the empty directory wasn't copied, but it wasn't detected when checking if the mod was enabled. When checking if a mod is enabled, I now disregard directories.  I couldn't use the standard path.toFile().isFile() method because that seems to require the file actually existing in the FS.

**Comment by apemanzilla** [comment]
Bit late but it seems to be working fine for me, thanks!

**Pull request merged**
