### PR TITLE
V2.0

### PR DESCRIPTION
**Pull request by oharaandrew314**
[Download TinkerTime v2.0.0-beta4](https://github.com/oharaandrew314/TinkerTime/releases/download/v2.0.0-beta4/TinkerTime.v2.0.0-beta4.zip)

This is basically a total rewrite, so everything must be tested!
@cgruber and @apemanzilla, would you care to take a look and see what you think?

#### v2.0 Changelog

This Major Update converts TinkerTime to use the pure-java H2 Database engine. TinkerTime will now run much faster, as more data can be cached, rather than constantly analyzing the mod zip files.

###### LEGACY BREAKING CHANGES:

You will need to re-install all your mods. Fortunately, you can import your legacy TinkerTime-mods.json files, which are stored in Kerbal Space Program/TinkerTime. This will help make for a smoother transition. In the future, the database will be automatically migrated for changes.

- New Features
  - Faster due to the H2 database engine migration
    - you may notice that mod info in the right panel switches far faster than before
  - Proper Installation Management
    - TinkerTime will now keep track of multiple KSP installations, and can switch them on the fly
  - You can now filter your mods with a text filter
  - New Splash screen on startup
  - New App Icons based on splash screen
  - You can now import mod URLs from a plain-text file
  - You can now export all of your mods, rather than just enabled ones

- Bug Fixes
  - Links to KerbalStuff mods will no longer go to the API page

- Other interesting points
  - app is now packaged in io.andrewohara.tinkertime
  - Much deeper dependency injection migration for easier maintenance and development
  - Major refactor in an attempt to increase maintainability
  - Mod Images and readme text is now stored directly in the database

### CODE REVIEW

**Comment by apemanzilla** [comment]
I'll start testing this once I get KSP installed again - rebuilt my OS last week.

**Comment by oharaandrew314** [comment]
No rush.  I've actually gone and torn apart the ORM again and introduced some inexplicable bugs.

So, testing this beta would probably be a waste of time, but you can let me know what you think of the updated design.

**Comment by oharaandrew314** [comment]
Ok, it seems to be stable again.

**Comment by apemanzilla** [comment]
Minor issue right off the bat - ModuleManager doesn't show up properly until downloaded.
Image

**Comment by oharaandrew314** [comment]
Well, that's expected.  Would it be better if I auto-download it?

**Comment by apemanzilla** [comment]
I'd say so, as it's almost always necessary in modded installs, and if for some reason a user doesn't want it they can just disable it.

**Comment by oharaandrew314** [comment]
Ok, I'll see if I can get that added in.

**Comment by apemanzilla** [comment]
Also minor, but the items in the "Options" menu are misaligned:
Image
... and there's also some occasional ghosting in menus - in this screenshot, I've already clicked "Check for Mod Updates" but the menu remains drawn. If you hover over a button they are redrawn over the "ghost" menu. (Maybe force a repaint of the entire frame?):
Image

**Comment by oharaandrew314** [comment]
Yeah, I've noticed both of those.  I think I just thought up of a solution
for the first problem.

Thanks for the screenshots.  They're helpful.

**Comment by apemanzilla** [comment]
No problem - still testing right now, no other issues. One suggestion I have however is for mods with multiple downloads (e.g. [Active Texture Management on GitHub](https://github.com/rbray89/ActiveTextureManagement/releases)) add a label to the info page that shows which variant is being used, and an option to select a different one.

**Comment by oharaandrew314** [comment]
That's a good idea.

**Comment by oharaandrew314** [comment]
Made some updates.  See commits above.  I'm not going to add an indicator for the selected asset right now, and I haven't been able to reproduce the menu ghosting enough to fix it.

**Comment by oharaandrew314** [comment]
Oh, hold on.  I forgot to auto-download ModuleManager when setting up new installations.  I'll do that now.

**Comment by apemanzilla** [comment]
In beta 3, TT now detects an update for ModuleManager on the first start, but does not download it. Not sure if this is intended behavior.
Image

**Comment by oharaandrew314** [comment]
Yeah, I just said that I forgot to get it to download on first start.  Still working on that.

**Comment by apemanzilla** [comment]
Ah, thought you had added it. I have to pay attention to the commits more.

Additionally, I can't enable Active Texture Management any more. I added it and Remote Tech, and chose the aggressive version. I can enable/disable ModuleManager and Remote Tech, but not Active Texture Management.

This does not occur with single-version Github mods such as Karbonite.

**Comment by oharaandrew314** [comment]
Hmm, I'll look into that, too.  Thanks for the reports.

**Comment by oharaandrew314** [comment]
It works for me?
capture

**Comment by oharaandrew314** [comment]
Ok, I've pushed the auto Module Manager download.

**Comment by apemanzilla** [comment]
Hmm, seems like it didn't download the mod. Updating it fixed the issue.

**Comment by oharaandrew314** [comment]
Ah.

**Comment by apemanzilla** [comment]
By the way, is that Windows explorer in Chrome? How did you do that?

**Comment by oharaandrew314** [comment]
Kind of.  Checkout out [Clover 3](http://ejie.me/).  It's an absolute standard of mine.

**Comment by apemanzilla** [comment]
Thanks, that looks sweet! I'll have to try it out.

**Comment by oharaandrew314** [comment]
@foonix, if you're still interested in testing, v2.0.0-beta4 is available in this PR.

**Comment by cgruber** [comment]
Sorry I've been out of the loop.  Shifts at work have left me with less
time to focus on things like this.

**Pull request merged**
