### PR TITLE
Updates for custom version checker

### PR DESCRIPTION
**Pull request by iulianov**
The current version checking code is broken for some mods on curseforge
http://www.curse.com/ksp-mods/kerbal/223730-kerbol-positioning-system
http://www.curse.com/ksp-mods/kerbal/220289-kerbal-alarm-clock

Since you are only using it to compare version numbers I have written some custom code that allows mods with versions that do not conform to the semver standard.

This is not just a compatibility request though. With the code used in VersionParser TinkerTime would mistakenly use old versions of mods under certain conditions:
old mod version: `<1.0.1.21>`
new mod version `<1.0.10.1>`
The code in VersionParser that made sure there are exactly 3 version numbers would create the following version strings:
`<1.0.121>`(old) and `<1.0.101>`(new)
This would cause the jsemver code to conclude that the old file is actually newer than the new file.

There is another pull request for the Common submodule that provides the actual Version checker code.

B.T.W: This change would close the following issue: https://github.com/oharaandrew314/TinkerTime/issues/221

### CODE REVIEW

**Comment by oharaandrew314** [comment]
You need to update the submodule reference

**Comment by iulianov** [comment]
Completely forgot the debug. Ill create another request in a minute.
As for the build failing - I did not want to check in the .gitmodules file since it points to my copy of the Common repo.
Just tell me if you want me to update it anyway so that the autobuild succeeds.

**Comment by oharaandrew314** [comment]
To update the submodule reference, you just need to do `git add Common`

**Comment by iulianov** [comment]
The code compiles on my machine since I have the Common submodule pointed at my version that has the necessary changes.
I am not sure what you mean by `<git add Common>`. Since I have changes to Common that I need to push I need to make sure that those changes get pushed my branch on github instead of yours.

**Comment by oharaandrew314** [comment]
Yeah, maybe this is more complicated than I think.  After the Common PR is merged, I'll just update the reference myself.

**Comment by iulianov** [comment]
ok, let me create a new PR for both

**Comment by iulianov** [comment]
Do I need to reissue the pull request? It seems that it now contains both commits.

**Comment by oharaandrew314** [comment]
No need.  The new commit is here.

**Comment by oharaandrew314** [comment]
[The Build](https://travis-ci.org/oharaandrew314/TinkerTime/builds/60789584) passed.  Thanks for contributing!

**Comment by iulianov** [comment]
Glad to be of use for such a useful tool.

**Comment by oharaandrew314** [comment]
Well, I'm glad that you like it!  I'll probably include this in a maintenance release once I fix a swing issue.  I've been ignoring it for a while since the error doesn't cause a failure for the end-user, but it's annoying me too much now.

**Pull request merged**
