### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by apemanzilla**
This PR:

- Fixes a typo
- Adds an option to run KSP in a borderless window (Only available on Windows)
- Removes button focus borders

### CODE REVIEW

**Comment by oharaandrew314** [comment]
What does the "render button focus" thing do?

**Comment by apemanzilla** [comment]
Render button focus means after clicking a button you won't get the persistent blue border around it. Borderless mode only works if KSP is set to "Windowed" mode (Can't control that with launch arguments) and should work for either version.

**Comment by oharaandrew314** [comment]
Ok, do you think you can make a note on the options window, stating that it will only affect windowed mode?

**Comment by apemanzilla** [comment]
Yep, hold on

**Comment by oharaandrew314** [comment]
Thanks!

**Comment by apemanzilla** [comment]
Alright. Another option could be to have it automatically disable full screen by editing KSP's config.

**Pull request merged**
