### PR TITLE
migrate to guice framework

### PR DESCRIPTION
**Pull request by oharaandrew314**

### CODE REVIEW

**Comment by cgruber** [comment]
Why!  Use dagger!  ;)

**Comment by oharaandrew314** [comment]
Says the second biggest contributor to guice!

Is Dagger essentially the same thing, but faster, and with a simpler API?

**Comment by cgruber** [comment]
But seriously - I had a branch for using Dagger 2, but didn't make a pull since you use gradle, and eclipse, and the gradle eclipse integration doesn't support annotation processing (yet).  

sigh...

**Comment by cgruber** [comment]
Yeah.  I'm not the second biggest contributor to Guice by a long shot, but I have been involved in both projects.  I'm the second biggest contributor to Dagger.

**Comment by oharaandrew314** [comment]
Hmm, it says you're the second biggest contributor to guice on the contributor page, but I guess that can be misleading!

It looks like the subset of the Guice API that I'm using is very close to the Dagger API, so maybe I'll switch over once I'm done with the migration to the H2 database!

**Comment by cgruber** [comment]
Oh - that's partly misleading, since a lot of our internal changes weren't credited properly until we updated MOE (our sync tool) to show the commit author, not the committer.  So most of the code you are seeing is not my personal origin, I just did the sync out to codesite/github. 

I'm happy to do the migration to Dagger, though I'm not on that team anymore (I'm still on the same wider team).  But I don't want to do it until https://issuetracker.springsource.com/browse/STS-3925 is fixed, so that people who use gradle and eclipse aren't stuck with a bad build, or manually configuring the .factorypath with all the annotation processor bits.

**Comment by oharaandrew314** [comment]
Ah, maybe that issue is why I have to ignore a bunch of annotation errors in STS at work.  I have a feeling that the resolution to that won't affect the vanilla eclipse, though, would it?

**Comment by oharaandrew314** [comment]
@cgruber, is this the Eclipse error you were referring to?

capture

**Pull request merged**
